sudo: false
dist: trusty

bundler_args: --without documentation
language: ruby
rvm:
 - 2.2.8
 - 2.3.5
 - 2.4.2
 - 2.5
 - 2.6
 - 2.7
 - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  irc:
    channels:
      - "irc.freenode.org#r509"
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: always
